# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(blank=True, max_length=30, verbose_name='mac')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='last time')),
                ('code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validate.Code', verbose_name='code')),
            ],
        ),
    ]
